// This holds a list of fiction Country
// You can use data fetched from a database or cloud as well

final List<Map<String, dynamic>> allConutry = [
  {"code":004 , "shortName": "АФГАНИСТАН", "alpha_3": "AFG"},
  {"code":008 , "shortName": "АЛБАНИЯ", "alpha_3": "ALB"},
  {"code":010 , "shortName": "АНТАРКТИДА", "alpha_3": "ATA"},
  {"code":012 , "shortName": "АЛЖИР", "alpha_3": "DZA"},
  {"code":016 , "shortName": "АМЕРИКАНСКОЕ САМОА", "alpha_3": "ASM"},
  {"code":020 , "shortName": "АНДОРРА", "alpha_3": "AND"},
  {"code":024 , "shortName": "АНГОЛА", "alpha_3": "AGO"},
  {"code":028 , "shortName": "АНТИГУА И БАРБУДА", "alpha_3": "ATG"},
  {"code":031 , "shortName": "АЗЕРБАЙДЖАН", "alpha_3": "AZE"},
  {"code":032 , "shortName": "АРГЕНТИНА", "alpha_3": "ARG"},
  {"code":036 , "shortName": "АВСТРАЛИЯ", "alpha_3": "AUS"},
  {"code":040 , "shortName": "АВСТРИЯ", "alpha_3": "AUT"},
  {"code":044 , "shortName": "БАГАМЫ", "alpha_3": "BHS"},
  {"code":048 , "shortName": "БАХРЕЙН", "alpha_3": "BHR"},
  {"code":050 , "shortName": "БАНГЛАДЕШ", "alpha_3": "BGD"},
  {"code":051 , "shortName": "АРМЕНИЯ", "alpha_3": "ARM"},
  {"code":052 , "shortName": "БАРБАДОС", "alpha_3": "BRB"},
  {"code":056 , "shortName": "БЕЛЬГИЯ", "alpha_3": "BEL"},
  {"code":060 , "shortName": "БЕРМУДЫ", "alpha_3": "BMU"},
  {"code":064 , "shortName": "БУТАН", "alpha_3": "BTN"},
  {"code":068 , "shortName": "БОЛИВИЯ, МНОГОНАЦИОНАЛЬНОЕ ГОСУДАРСТВО", "alpha_3": "BOL"},
  {"code":070 , "shortName": "БОСНИЯ И ГЕРЦЕГОВИНА", "alpha_3": "BIH"},
  {"code":072 , "shortName": "БОТСВАНА", "alpha_3": "BWA"},
  {"code":074 , "shortName": "ОСТРОВ БУВЕ", "alpha_3": "BVT"},
  {"code":076 , "shortName": "БРАЗИЛИЯ", "alpha_3": "BRA"},
  {"code":084 , "shortName": "БЕЛИЗ", "alpha_3": "BLZ"},
  {"code":086 , "shortName": "БРИТАНСКАЯ ТЕРРИТОРИЯ В ИНДИЙСКОМ ОКЕАНЕ", "alpha_3": "IOT"},
  {"code":090 , "shortName": "СОЛОМОНОВЫ ОСТРОВА", "alpha_3": "SLB"},
  {"code":092 , "shortName": "ВИРГИНСКИЕ ОСТРОВА (БРИТАНСКИЕ)", "alpha_3": "VGB"},
  {"code":096 , "shortName": "БРУНЕЙ-ДАРУССАЛАМ", "alpha_3": "BRN"},
  {"code":100 , "shortName": "БОЛГАРИЯ", "alpha_3": "BGR"},
  {"code":104 , "shortName": "МЬЯНМА", "alpha_3": "MMR"},
  {"code":108 , "shortName": "БУРУНДИ", "alpha_3": "BDI"},
  {"code":112 , "shortName": "БЕЛАРУСЬ", "alpha_3": "BLR"},
  {"code":116 , "shortName": "КАМБОДЖА", "alpha_3": "KHM"},
  {"code":120 , "shortName": "КАМЕРУН", "alpha_3": "CMR"},
  {"code":124 , "shortName": "КАНАДА", "alpha_3": "CAN"},
  {"code":132 , "shortName": "КАБО-ВЕРДЕ", "alpha_3": "CPV"},
  {"code":136 , "shortName": "ОСТРОВА КАЙМАН", "alpha_3": "CYM"},
  {"code":140 , "shortName": "ЦЕНТРАЛЬНО-АФРИКАНСКАЯ РЕСПУБЛИКА", "alpha_3": "CAF"},
  {"code":144 , "shortName": "ШРИ-ЛАНКА", "alpha_3": "LKA"},
  {"code":148 , "shortName": "ЧАД", "alpha_3": "TCD"},
  {"code":152 , "shortName": "ЧИЛИ", "alpha_3": "CHL"},
  {"code":156 , "shortName": "КИТАЙ", "alpha_3": "CHN"},
  {"code":158 , "shortName": "ТАЙВАНЬ (КИТАЙ)", "alpha_3": "TWN"},
  {"code":162 , "shortName": "ОСТРОВ РОЖДЕСТВА", "alpha_3": "CXR"},
  {"code":166 , "shortName": "КОКОСОВЫЕ (КИЛИНГ) ОСТРОВА", "alpha_3": "CCK"},
  {"code":170 , "shortName": "КОЛУМБИЯ", "alpha_3": "COL"},
  {"code":174 , "shortName": "КОМОРЫ", "alpha_3": "COM"},
  {"code":175 , "shortName": "МАЙОТТА", "alpha_3": "MYT"},
  {"code":178 , "shortName": "КОНГО", "alpha_3": "COG"},
  {"code":180 , "shortName": "КОНГО, ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА", "alpha_3": "COD"},
  {"code":184 , "shortName": "ОСТРОВА КУКА", "alpha_3": "COK"},
  {"code":188 , "shortName": "КОСТА-РИКА", "alpha_3": "CRI"},
  {"code":191 , "shortName": "ХОРВАТИЯ", "alpha_3": "HRV"},
  {"code":192 , "shortName": "КУБА", "alpha_3": "CUB"},
  {"code":196 , "shortName": "КИПР", "alpha_3": "CYP"},
  {"code":203 , "shortName": "ЧЕХИЯ", "alpha_3": "CZE"},
  {"code":204 , "shortName": "БЕНИН", "alpha_3": "BEN"},
  {"code":208 , "shortName": "ДАНИЯ", "alpha_3": "DNK"},
  {"code":212 , "shortName": "ДОМИНИКА", "alpha_3": "DMA"},
  {"code":214 , "shortName": "ДОМИНИКАНСКАЯ РЕСПУБЛИКА", "alpha_3": "DOM"},
  {"code":218 , "shortName": "ЭКВАДОР", "alpha_3": "ECU"},
  {"code":222 , "shortName": "ЭЛЬ-САЛЬВАДОР", "alpha_3": "SLV"},
  {"code":226 , "shortName": "ЭКВАТОРИАЛЬНАЯ ГВИНЕЯ", "alpha_3": "GNQ"},
  {"code":231 , "shortName": "ЭФИОПИЯ", "alpha_3": "ETH"},
  {"code":232 , "shortName": "ЭРИТРЕЯ", "alpha_3": "ERI"},
  {"code":233 , "shortName": "ЭСТОНИЯ", "alpha_3": "EST"},
  {"code":234 , "shortName": "ФАРЕРСКИЕ ОСТРОВА", "alpha_3": "FRO"},
  {"code":238 , "shortName": "ФОЛКЛЕНДСКИЕ ОСТРОВА (МАЛЬВИНСКИЕ)", "alpha_3": "FLK"},
  {"code":239 , "shortName": "ЮЖНАЯ ДЖОРДЖИЯ И ЮЖНЫЕ САНДВИЧЕВЫ ОСТРОВА", "alpha_3": "SGS"},
  {"code":242 , "shortName": "ФИДЖИ", "alpha_3": "FJI"},
  {"code":246 , "shortName": "ФИНЛЯНДИЯ", "alpha_3": "FIN"},
  {"code":248 , "shortName": "ЭЛАНДСКИЕ ОСТРОВА", "alpha_3": "ALA"},
  {"code":250 , "shortName": "ФРАНЦИЯ", "alpha_3": "FRA"},
  {"code":254 , "shortName": "ФРАНЦУЗСКАЯ ГВИАНА", "alpha_3": "GUF"},
  {"code":258 , "shortName": "ФРАНЦУЗСКАЯ ПОЛИНЕЗИЯ", "alpha_3": "PYF"},
  {"code":260 , "shortName": "ФРАНЦУЗСКИЕ ЮЖНЫЕ ТЕРРИТОРИИ", "alpha_3": "ATF"},
  {"code":262 , "shortName": "ДЖИБУТИ", "alpha_3": "DJI"},
  {"code":266 , "shortName": "ГАБОН", "alpha_3": "GAB"},
  {"code":268 , "shortName": "ГРУЗИЯ", "alpha_3": "GEO"},
  {"code":270 , "shortName": "ГАМБИЯ", "alpha_3": "GMB"},
  {"code":275 , "shortName": "ПАЛЕСТИНА, ГОСУДАРСТВО", "alpha_3": "PSE"},
  {"code":276 , "shortName": "ГЕРМАНИЯ", "alpha_3": "DEU"},
  {"code":288 , "shortName": "ГАНА", "alpha_3": "GHA"},
  {"code":292 , "shortName": "ГИБРАЛТАР", "alpha_3": "GIB"},
  {"code":296 , "shortName": "КИРИБАТИ", "alpha_3": "KIR"},
  {"code":300 , "shortName": "ГРЕЦИЯ", "alpha_3": "GRC"},
  {"code":304 , "shortName": "ГРЕНЛАНДИЯ", "alpha_3": "GRL"},
  {"code":308 , "shortName": "ГРЕНАДА", "alpha_3": "GRD"},
  {"code":312 , "shortName": "ГВАДЕЛУПА", "alpha_3": "GLP"},
  {"code":316 , "shortName": "ГУАМ", "alpha_3": "GUM"},
  {"code":320 , "shortName": "ГВАТЕМАЛА", "alpha_3": "GTM"},
  {"code":324 , "shortName": "ГВИНЕЯ", "alpha_3": "GIN"},
  {"code":328 , "shortName": "ГАЙАНА", "alpha_3": "GUY"},
  {"code":332 , "shortName": "ГАИТИ", "alpha_3": "HTI"},
  {"code":334 , "shortName": "ОСТРОВ ХЕРД И ОСТРОВА МАКДОНАЛЬД", "alpha_3": "HMD"},
  {"code":336 , "shortName": "ПАПСКИЙ ПРЕСТОЛ (ГОСУДАРСТВО - ГОРОД ВАТИКАН)", "alpha_3": "VAT"},
  {"code":340 , "shortName": "ГОНДУРАС", "alpha_3": "HND"},
  {"code":344 , "shortName": "ГОНКОНГ", "alpha_3": "HKG"},
  {"code":348 , "shortName": "ВЕНГРИЯ", "alpha_3": "HUN"},
  {"code":352 , "shortName": "ИСЛАНДИЯ", "alpha_3": "ISL"},
  {"code":356 , "shortName": "ИНДИЯ", "alpha_3": "IND"},
  {"code":360 , "shortName": "ИНДОНЕЗИЯ", "alpha_3": "IDN"},
  {"code":364 , "shortName": "ИРАН (ИСЛАМСКАЯ РЕСПУБЛИКА)", "alpha_3": "IRN"},
  {"code":368 , "shortName": "ИРАК", "alpha_3": "IRQ"},
  {"code":372 , "shortName": "ИРЛАНДИЯ", "alpha_3": "IRL"},
  {"code":376 , "shortName": "ИЗРАИЛЬ", "alpha_3": "ISR"},
  {"code":380 , "shortName": "ИТАЛИЯ", "alpha_3": "ITA"},
  {"code":384 , "shortName": "КОТ Д'ИВУАР", "alpha_3": "CIV"},
  {"code":388 , "shortName": "ЯМАЙКА", "alpha_3": "JAM"},
  {"code":392 , "shortName": "ЯПОНИЯ", "alpha_3": "JPN"},
  {"code":398 , "shortName": "КАЗАХСТАН", "alpha_3": "KAZ"},
  {"code":400 , "shortName": "ИОРДАНИЯ", "alpha_3": "JOR"},
  {"code":404 , "shortName": "КЕНИЯ", "alpha_3": "KEN"},
  {"code":408 , "shortName": "КОРЕЯ, НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА", "alpha_3": "PRK"},
  {"code":410 , "shortName": "КОРЕЯ, РЕСПУБЛИКА", "alpha_3": "KOR"},
  {"code":414 , "shortName": "КУВЕЙТ", "alpha_3": "KWT"},
  {"code":417 , "shortName": "КИРГИЗИЯ", "alpha_3": "KGZ"},
  {"code":418 , "shortName": "ЛАОССКАЯ НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА", "alpha_3": "LAO"},
  {"code":422 , "shortName": "ЛИВАН", "alpha_3": "LBN"},
  {"code":426 , "shortName": "ЛЕСОТО", "alpha_3": "LSO"},
  {"code":428 , "shortName": "ЛАТВИЯ", "alpha_3": "LVA"},
  {"code":430 , "shortName": "ЛИБЕРИЯ", "alpha_3": "LBR"},
  {"code":434 , "shortName": "ЛИВИЯ", "alpha_3": "LBY"},
  {"code":438 , "shortName": "ЛИХТЕНШТЕЙН", "alpha_3": "LIE"},
  {"code":440 , "shortName": "ЛИТВА", "alpha_3": "LTU"},
  {"code":442 , "shortName": "ЛЮКСЕМБУРГ", "alpha_3": "LUX"},
  {"code":446 , "shortName": "МАКАО", "alpha_3": "MAC"},
  {"code":450 , "shortName": "МАДАГАСКАР", "alpha_3": "MDG"},
  {"code":454 , "shortName": "МАЛАВИ", "alpha_3": "MWI"},
  {"code":458 , "shortName": "МАЛАЙЗИЯ", "alpha_3": "MYS"},
  {"code":462 , "shortName": "МАЛЬДИВЫ", "alpha_3": "MDV"},
  {"code":466 , "shortName": "МАЛИ", "alpha_3": "MLI"},
  {"code":470 , "shortName": "МАЛЬТА", "alpha_3": "MLT"},
  {"code":474 , "shortName": "МАРТИНИКА", "alpha_3": "MTQ"},
  {"code":478 , "shortName": "МАВРИТАНИЯ", "alpha_3": "MRT"},
  {"code":480 , "shortName": "МАВРИКИЙ", "alpha_3": "MUS"},
  {"code":484 , "shortName": "МЕКСИКА", "alpha_3": "MEX"},
  {"code":492 , "shortName": "МОНАКО", "alpha_3": "MCO"},
  {"code":496 , "shortName": "МОНГОЛИЯ", "alpha_3": "MNG"},
  {"code":498 , "shortName": "МОЛДОВА, РЕСПУБЛИКА", "alpha_3": "MDA"},
  {"code":499 , "shortName": "ЧЕРНОГОРИЯ", "alpha_3": "MNE"},
  {"code":500 , "shortName": "МОНТСЕРРАТ", "alpha_3": "MSR"},
  {"code":504 , "shortName": "МАРОККО", "alpha_3": "MAR"},
  {"code":508 , "shortName": "МОЗАМБИК", "alpha_3": "MOZ"},
  {"code":512 , "shortName": "ОМАН", "alpha_3": "OMN"},
  {"code":516 , "shortName": "НАМИБИЯ", "alpha_3": "NAM"},
  {"code":520 , "shortName": "НАУРУ", "alpha_3": "NRU"},
  {"code":524 , "shortName": "НЕПАЛ", "alpha_3": "NPL"},
  {"code":528 , "shortName": "НИДЕРЛАНДЫ", "alpha_3": "NLD"},
  {"code":531 , "shortName": "КЮРАСАО", "alpha_3": "CUW"},
  {"code":533 , "shortName": "АРУБА", "alpha_3": "ABW"},
  {"code":534 , "shortName": "СЕН-МАРТЕН (нидерландская часть)", "alpha_3": "SXM"},
  {"code":535 , "shortName": "БОНЭЙР, СИНТ-ЭСТАТИУС И САБА", "alpha_3": "BES"},
  {"code":540 , "shortName": "НОВАЯ КАЛЕДОНИЯ", "alpha_3": "NCL"},
  {"code":548 , "shortName": "ВАНУАТУ", "alpha_3": "VUT"},
  {"code":554 , "shortName": "НОВАЯ ЗЕЛАНДИЯ", "alpha_3": "NZL"},
  {"code":558 , "shortName": "НИКАРАГУА", "alpha_3": "NIC"},
  {"code":562 , "shortName": "НИГЕР", "alpha_3": "NER"},
  {"code":566 , "shortName": "НИГЕРИЯ", "alpha_3": "NGA"},
  {"code":570 , "shortName": "НИУЭ", "alpha_3": "NIU"},
  {"code":574 , "shortName": "ОСТРОВ НОРФОЛК", "alpha_3": "NFK"},
  {"code":578 , "shortName": "НОРВЕГИЯ", "alpha_3": "NOR"},
  {"code":580 , "shortName": "СЕВЕРНЫЕ МАРИАНСКИЕ ОСТРОВА", "alpha_3": "MNP"},
  {"code":581 , "shortName": "МАЛЫЕ ТИХООКЕАНСКИЕ ОТДАЛЕННЫЕ ОСТРОВА СОЕДИНЕННЫХ ШТАТОВ", "alpha_3": "UMI"},
  {"code":583 , "shortName": "МИКРОНЕЗИЯ, ФЕДЕРАТИВНЫЕ ШТАТЫ", "alpha_3": "FSM"},
  {"code":584 , "shortName": "МАРШАЛЛОВЫ ОСТРОВА", "alpha_3": "MHL"},
  {"code":585 , "shortName": "ПАЛАУ", "alpha_3": "PLW"},
  {"code":586 , "shortName": "ПАКИСТАН", "alpha_3": "PAK"},
  {"code":591 , "shortName": "ПАНАМА", "alpha_3": "PAN"},
  {"code":598 , "shortName": "ПАПУА-НОВАЯ ГВИНЕЯ", "alpha_3": "PNG"},
  {"code":600 , "shortName": "ПАРАГВАЙ", "alpha_3": "PRY"},
  {"code":604 , "shortName": "ПЕРУ", "alpha_3": "PER"},
  {"code":608 , "shortName": "ФИЛИППИНЫ", "alpha_3": "PHL"},
  {"code":612 , "shortName": "ПИТКЕРН", "alpha_3": "PCN"},
  {"code":616 , "shortName": "ПОЛЬША", "alpha_3": "POL"},
  {"code":620 , "shortName": "ПОРТУГАЛИЯ", "alpha_3": "PRT"},
  {"code":624 , "shortName": "ГВИНЕЯ-БИСАУ", "alpha_3": "GNB"},
  {"code":626 , "shortName": "ТИМОР-ЛЕСТЕ", "alpha_3": "TLS"},
  {"code":630 , "shortName": "ПУЭРТО-РИКО", "alpha_3": "PRI"},
  {"code":634 , "shortName": "КАТАР", "alpha_3": "QAT"},
  {"code":638 , "shortName": "РЕЮНЬОН", "alpha_3": "REU"},
  {"code":642 , "shortName": "РУМЫНИЯ", "alpha_3": "ROU"},
  {"code":643 , "shortName": "РОССИЯ", "alpha_3": "RUS"},
  {"code":646 , "shortName": "РУАНДА", "alpha_3": "RWA"},
  {"code":652 , "shortName": "СЕН-БАРТЕЛЕМИ", "alpha_3": "BLM"},
  {"code":654 , "shortName": "СВЯТАЯ ЕЛЕНА, ОСТРОВ ВОЗНЕСЕНИЯ, ТРИСТАН-ДА-КУНЬЯ", "alpha_3": "SHN"},
  {"code":659 , "shortName": "СЕНТ-КИТС И НЕВИС", "alpha_3": "KNA"},
  {"code":660 , "shortName": "АНГИЛЬЯ", "alpha_3": "AIA"},
  {"code":662 , "shortName": "СЕНТ-ЛЮСИЯ", "alpha_3": "LCA"},
  {"code":663 , "shortName": "СЕН-МАРТЕН (французская часть)", "alpha_3": "MAF"},
  {"code":666 , "shortName": "СЕН-ПЬЕР И МИКЕЛОН", "alpha_3": "SPM"},
  {"code":670 , "shortName": "СЕНТ-ВИНСЕНТ И ГРЕНАДИНЫ", "alpha_3": "VCT"},
  {"code":674 , "shortName": "САН-МАРИНО", "alpha_3": "SMR"},
  {"code":678 , "shortName": "САН-ТОМЕ И ПРИНСИПИ", "alpha_3": "STP"},
  {"code":682 , "shortName": "САУДОВСКАЯ АРАВИЯ", "alpha_3": "SAU"},
  {"code":686 , "shortName": "СЕНЕГАЛ", "alpha_3": "SEN"},
  {"code":688 , "shortName": "СЕРБИЯ", "alpha_3": "SRB"},
  {"code":690 , "shortName": "СЕЙШЕЛЫ", "alpha_3": "SYC"},
  {"code":694 , "shortName": "СЬЕРРА-ЛЕОНЕ", "alpha_3": "SLE"},
  {"code":702 , "shortName": "СИНГАПУР", "alpha_3": "SGP"},
  {"code":703 , "shortName": "СЛОВАКИЯ", "alpha_3": "SVK"},
  {"code":704 , "shortName": "ВЬЕТНАМ", "alpha_3": "VNM"},
  {"code":705 , "shortName": "СЛОВЕНИЯ", "alpha_3": "SVN"},
  {"code":706 , "shortName": "СОМАЛИ", "alpha_3": "SOM"},
  {"code":710 , "shortName": "ЮЖНАЯ АФРИКА", "alpha_3": "ZAF"},
  {"code":716 , "shortName": "ЗИМБАБВЕ", "alpha_3": "ZWE"},
  {"code":724 , "shortName": "ИСПАНИЯ", "alpha_3": "ESP"},
  {"code":732 , "shortName": "ЗАПАДНАЯ САХАРА", "alpha_3": "ESH"},
  {"code":729 , "shortName": "СУДАН", "alpha_3": "SDN"},
  {"code":740 , "shortName": "СУРИНАМ", "alpha_3": "SUR"},
  {"code":744 , "shortName": "ШПИЦБЕРГЕН И ЯН МАЙЕН", "alpha_3": "SJM"},
  {"code":748 , "shortName": "ЭСВАТИНИ", "alpha_3": "SWZ"},
  {"code":752 , "shortName": "ШВЕЦИЯ", "alpha_3": "SWE"},
  {"code":756 , "shortName": "ШВЕЙЦАРИЯ", "alpha_3": "CHE"},
  {"code":760 , "shortName": "СИРИЙСКАЯ АРАБСКАЯ РЕСПУБЛИКА", "alpha_3": "SYR"},
  {"code":762 , "shortName": "ТАДЖИКИСТАН", "alpha_3": "TJK"},
  {"code":764 , "shortName": "ТАИЛАНД", "alpha_3": "THA"},
  {"code":768 , "shortName": "ТОГО", "alpha_3": "TGO"},
  {"code":772 , "shortName": "ТОКЕЛАУ", "alpha_3": "TKL"},
  {"code":776 , "shortName": "ТОНГА", "alpha_3": "TON"},
  {"code":780 , "shortName": "ТРИНИДАД И ТОБАГО", "alpha_3": "TTO"},
  {"code":784 , "shortName": "ОБЪЕДИНЕННЫЕ АРАБСКИЕ ЭМИРАТЫ", "alpha_3": "ARE"},
  {"code":788 , "shortName": "ТУНИС", "alpha_3": "TUN"},
  {"code":792 , "shortName": "ТУРЦИЯ", "alpha_3": "TUR"},
  {"code":795 , "shortName": "ТУРКМЕНИСТАН", "alpha_3": "TKM"},
  {"code":796 , "shortName": "ОСТРОВА ТЕРКС И КАЙКОС", "alpha_3": "TCA"},
  {"code":798 , "shortName": "ТУВАЛУ", "alpha_3": "TUV"},
  {"code":800 , "shortName": "УГАНДА", "alpha_3": "UGA"},
  {"code":804 , "shortName": "УКРАИНА", "alpha_3": "UKR"},
  {"code":807 , "shortName": "СЕВЕРНАЯ МАКЕДОНИЯ", "alpha_3": "MKD"},
  {"code":818 , "shortName": "ЕГИПЕТ", "alpha_3": "EGY"},
  {"code":826 , "shortName": "СОЕДИНЕННОЕ КОРОЛЕВСТВО", "alpha_3": "GBR"},
  {"code":831 , "shortName": "ГЕРНСИ", "alpha_3": "GGY"},
  {"code":832 , "shortName": "ДЖЕРСИ", "alpha_3": "JEY"},
  {"code":833 , "shortName": "ОСТРОВ МЭН", "alpha_3": "IMN"},
  {"code":834 , "shortName": "ТАНЗАНИЯ, ОБЪЕДИНЕННАЯ РЕСПУБЛИКА", "alpha_3": "TZA"},
  {"code":840 , "shortName": "СОЕДИНЕННЫЕ ШТАТЫ", "alpha_3": "USA"},
  {"code":850 , "shortName": "ВИРГИНСКИЕ ОСТРОВА (США)", "alpha_3": "VIR"},
  {"code":854 , "shortName": "БУРКИНА-ФАСО", "alpha_3": "BFA"},
  {"code":858 , "shortName": "УРУГВАЙ", "alpha_3": "URY"},
  {"code":860 , "shortName": "УЗБЕКИСТАН", "alpha_3": "UZB"},
  {"code":862 , "shortName": "ВЕНЕСУЭЛА (БОЛИВАРИАНСКАЯ РЕСПУБЛИКА)", "alpha_3": "VEN"},
  {"code":876 , "shortName": "УОЛЛИС И ФУТУНА", "alpha_3": "WLF"},
  {"code":882 , "shortName": "САМОА", "alpha_3": "WSM"},
  {"code":887 , "shortName": "ЙЕМЕН", "alpha_3": "YEM"},
  {"code":894 , "shortName": "ЗАМБИЯ", "alpha_3": "ZMB"},
  {"code":895 , "shortName": "АБХАЗИЯ", "alpha_3": "ABH"},
  {"code":896 , "shortName": "ЮЖНАЯ ОСЕТИЯ", "alpha_3": "OST"},
  {"code":728 , "shortName": "ЮЖНЫЙ СУДАН", "alpha_3": "SSD"}
];